import {StyleSheet, Dimensions} from 'react-native';
const {height, width} = Dimensions.get('screen');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  loginText: {
    fontSize: 24,
    alignSelf: 'center',
    marginTop: 65,
    fontWeight: 'bold',
    color: '#0A0618',
  },
  luckyMoonText: {
    alignSelf: 'center',
    marginTop: 59,
    color: '#E1E1E1',
    fontSize: 48,
    fontWeight: 'bold',
    letterSpacing: 0,
  },
  inputContainer: {
    marginTop: 82,
  },
  forgetPasswordText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000000',
  },
  buttonContainer: {
    justifyContent: 'flex-end',
    flex: 1,
  },
  signUpContainer: {
    height: 50,
    width: '85%',
    backgroundColor: 'white',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  signUpText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFCB3B',
  },
  loginContainer: {
    height: 50,
    width: '85%',
    backgroundColor: '#FD1B1B',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 6,
    marginBottom: 12,
  },
  loginbtnText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: 'bold',
  },
  eyeIcon: {
    position: 'absolute',
    right: 40,
    top: 12.99,
  },
  signupText: {
    fontSize: 24,
    color: '#0A0618',
    marginTop: 65,
    alignSelf: 'center',
    fontWeight: 'bold',
  },
  signupInputContainer: {
    marginTop: 36,
  },
  arrow: {
    position: 'absolute',
    right: 147,
    top: 18,
  },
  forgotPasswordText: {
    fontSize: 24,
    color: '#0A0618',
    textAlign: 'center',
    marginTop: 65,
    fontWeight: 'bold',
  },
  verificationCode: {
    fontSize: 16,
    color: '#000000',
    marginTop: 28,
    alignSelf: 'center',
  },
  emailInput: {
    height: 50,
    width: '85%',
    alignSelf: 'center',
    backgroundColor: '#F5F5F5',
    borderWidth: 1,
    borderColor: '#ffcb3b',
    marginTop: 34,
    fontSize: 16,
    borderRadius: 6,
  },
  arrowLeft: {
    position: 'absolute',
    top: 18,
    left: 147,
  },
  verificationText: {
    fontSize: 24,
    color: '#0A0618',
    textAlign: 'center',
    marginTop: 65,
    fontWeight: 'bold',
  },
  enterText: {
    fontSize: 16,
    marginTop: 28,
    alignSelf: 'center',
    overflow: 'hidden',
    color: '#000000',
  },

  codeFieldRoot: {marginTop: 37, alignSelf: 'center'},
  cell: {
    width: 57,
    height: 50,
    fontSize: 24,
    textAlign: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 6,
    paddingTop: 9,
    marginLeft: 6,
  },
  focusCell: {
    borderColor: '#FFCB3B',
    borderWidth: 1,
  },
  newPasswordText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#0A0618',
    marginTop: 65,
    alignSelf: 'center',
  },
  accountText: {
    fontSize: 16,
    alignSelf: 'center',
    color: '#000000',
    marginTop: 28,
  },
  termText: {
    marginTop: 12,
    fontSize: 16,
    color: '#A5A5A5',
    marginLeft: 35,
    marginRight: 37,
  },
  boarding1: {
    height: height * 0.5,
    width: '100%',
  },
  moonText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
    position: 'absolute',
    top: height * 0.415,
    alignSelf: 'center',
  },
  fastAndEasy: {
    fontSize: 22,
    textAlign: 'center',
    marginTop: height * 0.05,
    fontWeight: 'bold',
    color: '#141212',
  },
  advertisementText: {
    fontSize: 16,
    textAlign: 'center',
  },
  advertisementTextContainer: {
    marginTop: height * 0.05,
  },
  btnNext: {
    height: 50,
    backgroundColor: '#FD1B1B',
    width: '60%',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 6,
    elevation: 5,
    marginTop: height * 0.09,
  },
  btnNextText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: 'bold',
  },
  dotContainer: {
    marginTop: height * 0.05,
    alignSelf: 'center',
  },
  boarding2: {
    height: height * 0.49,
    width: '100%',
  },
  customizeText: {
    fontSize: 22,
    textAlign: 'center',
    marginTop: height * 0.06,
    fontWeight: 'bold',
    color: '#141212',
  },
  moonTextBlack: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#1D1717',
    position: 'absolute',
    top: height * 0.4,
    alignSelf: 'center',
  },
  moonText2: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
    position: 'absolute',
    top: height * 0.41,
    alignSelf: 'center',
  },
});

export default styles;
